   ALTER TABLE Nms_select ALTER COLUMN selectid SET DEFAULT nextval('id_seq');
    INSERT INTO Nms_select(label, options)
    VALUES('Probation Status', 'Inprobation'),
    ('Probation Status', 'Confirmed'),
    ('Gender', 'Male'),
    ('Gender', 'Female'),
    ('Gender', 'Others'),
    ('Employment Type', 'Full time'),
    ('Employment Type', 'Part time'),
    ('Employment Type', 'consultant'),
    ('Employment Type', 'Internship'),
    ('Work status', 'Remote'),
    ('Work status', 'Office'),
    ('Manager', 'Bimal'),
    ('Manager', 'Francis'),
    ('Manager', 'Mahesh'),
    ('Manager', 'Toby'),
    ('Manager', 'Sanoj'),
    ('Manager', 'Not Assigned'),
    ('Projects', 'NMS'),
    ('Projects', 'KESHER'),
    ('Projects', 'TOFEERIDE'),
    ('Projects', 'QNB'),
    ('Projects', 'BRANDING'),
    ('Projects', 'MAKISYS'),
    ('Projects', 'Not Assigned'),
    ('Designation', 'Junior Software Engineer'),
    ('Designation', 'Software Engineer'),
    ('Designation', 'Senior Software Engineer'),
    ('Designation', 'Intern'),
    ('Designation', 'Head - Accounts'),
    ('Designation', 'HR & Admin'),
    ('Designation', 'Assistant Manager - HR'),
    ('Designation', 'Manager HR'),
    ('Designation', 'Ui/Ux Designer'),
    ('Designation', 'Lead Ui/Ux Designer'),
    ('Designation', 'Brand Marketing Executies'),
    ('Designation', 'Copy Writer'),
    ('Designation', 'Senior Copy writer'),
    ('Designation', 'Business Analyst'),
    ('Designation', 'Project Manager'),
    ('Designation', 'Senior Project Manager'),
    ('Department', 'Tech Team'),
    ('Department', 'Human Resources'),
    ('Department', 'Accounts & Admin'),
    ('Department', 'Brand Marketing'),
    ('Department', 'Design Team'),
    ('Department', 'Project Management'),
    ('Department', 'Business Deelopment'),
    ('Lie Status', 'Punch In'),
    ('Lie Status', 'Punch Out'),
    ('Employee status', 'Active'),
    ('Employee status', 'Inactive'),
    ('Probation Period', '1'),
    ('Probation Period', '2'),
    ('Probation Period', '3'),
    ('Probation Period', '4'),
    ('Probation Period', '5'),
    ('Probation Period', '6'),
    ('Probation Period', '7'),
    ('Probation Period', '8'),
    ('Probation Period', '9'),
    ('Probation Period', '10'),
    ('Probation Period', '11'),
    ('Probation Period', '12');


